

[project]
name = "swarms"
version = "6.2.9"
description = "Swarms - Pytorch"
license = {text = "MIT License"}
authors = [ 
    { name = "Kye Gomez", email = "kye@swams.world" }, 
]
readme = "README.md"
keywords = [
    "artificial intelligence",
    "deep learning",
    "optimizers",
    "Prompt Engineering",
    "swarms",
    "agents",
    "llms",
    "transformers",
    "multi-agent",
    "swarms of agents",
    "Enterprise-Grade Agents",
    "Production-Grade Agents",
    "Agents",
    "Multi-Grade-Agents",
    "Swarms",
    "Transformers",
    "LLMs",
    "Prompt Engineering",
    "Agents",
    "Generative Agents",
    "Generative AI",
    "Agent Marketplace",
    "Agent Store",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.10,<4.0"


[dependency-groups]
lint = [
    "black<25.0,>=23.1",
    "ruff<0.7.4,>=0.5.1",
    "types-toml<1.0.0.0,>=0.10.8.1",
    "types-pytz<2025.0,>=2023.3",
    "types-chardet<6.0.0.0,>=5.0.4.6",
    "mypy-protobuf<4.0.0,>=3.0.0",
]
test = [
    "pytest<9.0.0,>=8.1.1",
    "termcolor<3.0.0,>=2.4.0",
    "pandas<3.0.0,>=2.2.2",
    "fastapi<0.116.0,>=0.110.1",
]


[project.urls]
homepage = "https://github.com/kyegomez/swarms"
repository = "https://github.com/kyegomez/swarms"
documentation = "https://docs.swarms.world"

[project.scripts]
swarms = "swarms.cli.main:main"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
torch = ">=2.1.1,<3.0"
transformers = ">= 4.39.0, <5.0.0"
asyncio = ">=3.4.3,<4.0"
langchain-community = "0.0.29"
langchain-experimental = "0.0.55"
backoff = "2.2.1"
toml = "*"
pypdf = "4.3.1"
loguru = "0.7.2"
pydantic = "2.8.2"
tenacity = "8.5.0"
Pillow = "10.4.0"
psutil = "*"
sentry-sdk = {version = "*", extras = ["http"]}  # Updated here
python-dotenv = "*"
PyYAML = "*"
docstring_parser = "0.16"
fastapi = "*"
openai = ">=1.30.1,<2.0"
termcolor = "*"
tiktoken = "*"
networkx = "*"
swarms-memory = "*"
black = "*"
aiofiles = "*"
swarm-models = "*"
clusterops = "*"
chromadb = "*"
reportlab = "*"
doc-master = "*"
rich = "*"

[tool.setuptools.packages.find]
where = ["swarms"]







[tool.ruff]
line-length = 70

[tool.black]
target-version = ["py38"]
line-length = 70
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''

