exclude = ["./playground", "./tests", "./scripts"]
line-length = 127

[lint]
ignore = []
select = ["E", "F", "W"]

[lint.per-file-ignores]
"./swarms/prompts/**.py" = ["E501", "W291", "W293"]
"./swarms/__init__.py" = ["F401"]
