<<<<<<< HEAD
=======
---
>>>>>>> 3d3dddaf0c7894ec2df14c51f7dd843c41c878c4
name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
<<<<<<< HEAD
        run: pip install -r requirements.txt

      - name: Run tests and checks
        run: |
          find tests/ -name "*.py" | xargs pytest
          pylint swarms
=======
        run: |
          pip install -r requirements.txt
          pip install pytest 

      - name: Run tests and checks
        run: |
          pytest
          pylint swarms
>>>>>>> 3d3dddaf0c7894ec2df14c51f7dd843c41c878c4
