name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
<<<<<<< HEAD
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python unit tests
      run: python3 -m unittest tests/
=======
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Python unit tests
      run: pytest
>>>>>>> 3d3dddaf0c7894ec2df14c51f7dd843c41c878c4

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile

    - name: Verify integration test results
<<<<<<< HEAD
      run: find tests/ -name "*.py" | xargs pytest
=======
      run: pytest
>>>>>>> 3d3dddaf0c7894ec2df14c51f7dd843c41c878c4
